version: '3.8'

services:
  app:
    build:
      context: ./talabalocation
    container_name: talaba_app
    volumes:
      - ./src:/var/www/html       # src papkani container ichida /var/www/html ga mount qilamiz
    networks:
      - talabalocation
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: talaba_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: talabalocation
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - talabalocation

  nginx:
    image: nginx:alpine
    container_name: talaba_nginx
    ports:
      - "8008:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html       # src papkani container ichida Nginx uchun ham mount qilamiz
    depends_on:
      - app
    networks:
      - talabalocation

volumes:
  dbdata:

networks:
  talabalocation:

