services:
  app:
    build:
      context: ./tezdoc
    container_name: tezdoc_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - tezdoc
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: tezdoc_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tezdoc
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "3310:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tezdoc

  nginx:
    image: nginx:alpine
    container_name: tezdoc_nginx
    ports:
      - "8010:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - tezdoc

volumes:
  dbdata:

networks:
  tezdoc:

