version: "3.9"

services:
  app:
    build:
      context: ./tezdoc
    container_name: tezdoc_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html       # Laravel kodlari
    networks:
      - tezdoc
    depends_on:
      - db
      - onlyoffice

  db:
    image: mysql:8.0
    container_name: tezdoc_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tezdoc
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "3310:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tezdoc

  nginx:
    image: nginx:alpine
    container_name: tezdoc_nginx
    ports:
      - "8010:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - tezdoc

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    environment:
    - JWT_ENABLED=true
    - JWT_SECRET=a7f3c9e2b1d4f6a8c5e7b9d1f3a5c7e9b2d4f6a8c1e3b5d7f9a2c4e6b8d1f3a5  # ✅ Bir xil
    - JWT_IN_BODY=true
    ports:
      - "8081:80"
    networks:
      - tezdoc

volumes:
  dbdata:

networks:
  tezdoc:
